//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apps
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Apps()
        {
            this.Words = new HashSet<Words>();
            this.Users = new HashSet<Users>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Website { get; set; }
        public string PublicKey { get; set; }
        public string SecureKey { get; set; }
        public Nullable<byte> IsEnabledForApi { get; set; }
        public Nullable<int> MaxRequestsByDay { get; set; }
        public string Logo { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Words> Words { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Users> Users { get; set; }
    }
}
