//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translations()
        {
            this.Votes = new HashSet<Votes>();
        }
    
        public int Id { get; set; }
        public int Word { get; set; }
        public string Value { get; set; }
        public int Language { get; set; }
    
        public virtual Languages Languages { get; set; }
        public virtual Words Words { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Votes> Votes { get; set; }
    }
}
