//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EpicApps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public int AccountType { get; set; }
        public string Name { get; set; }
        public string email { get; set; }
        public Nullable<byte> emailVerified { get; set; }
        public string gender { get; set; }
        public string profileLink { get; set; }
        public string locale { get; set; }
        public string PictureUrl { get; set; }
        public int AppID { get; set; }
        public string password { get; set; }
    
        public virtual Apps Apps { get; set; }
        public virtual UserType UserType { get; set; }
    }
}
